// src/views/Standings.vue
<template>
  <h2 class="text-2xl font-semibold">Tabelle</h2>
  <h3>{{ championship?.title }}</h3>
</template>

<script>
import {useFrontStore} from "@/store";

export default {
  name: 'Standings',
  setup() {
    const store = useFrontStore();

    return {
      championship: store.championship,
    };
  },
};
</script>

// src/feature/front-of-house/pages/Standings/index.tsx
import React from 'react';
import { useCurrentChampionship } from '@/api/hooks';
import { Ranking } from './components/ranking';

export function Standings() {
  const { data: championship } = useCurrentChampionship();
  return championship ? (
    <div>
      <h2 className="text-2xl font-semibold">
        {championship.title} -
        {championship.completed ? 'Abschlusstabelle' : 'Aktuelle Tabelle'}
      </h2>
      <Ranking championship={championship}></Ranking>
    </div>
  ) : null;
}
