// src/feature/front-of-house/pages/Standings.tsx
import React from 'react';
import { useFohData } from '../../../common/hooks';

export function Standings() {
  const { championship } = useFohData();

  return (
    <div>
      <h2 className="text-2xl font-semibold">
        {championship?.title} -
        {championship?.completed ? 'Abschlusstabelle' : 'Aktuelle Tabelle'}
      </h2>
    </div>
  );
}

// src/views/Standings.vue
<template>
  <h2 class="text-2xl font-semibold">Tabelle</h2>
  <h3>{{ championship?.title }}</h3>
</template>

<script>
import {useFrontStore} from "@/store";

export default {
  name: 'Standings',
  setup() {
    const store = useFrontStore();

    return {
      championship: store.championship,
    };
  },
};
</script>
