// src/views/foh/Standings.vue
<template>
  <h2 class="text-3xl">{{ championship?.title }} - Aktuelle Tabelle</h2>
</template>

<script>
import { computed } from 'vue'
import { useStore } from 'vuex';

export default {
  name: 'FohStandings',
  setup() {
    const store = useStore();
    return {
      championship: computed(() => store.state.currentChampionship)
    };
  }
}
</script>

// src/feature/front-of-house/pages/Standings.tsx
import React from 'react';
import { useFohData } from '../../../common/hooks';

export function Standings() {
  const { championship } = useFohData();

  return (
    <div>
      <h2 className="text-2xl font-semibold">
        {championship?.title} -
        {championship?.completed ? 'Abschlusstabelle' : 'Aktuelle Tabelle'}
      </h2>
    </div>
  );
}
